<?php
require_once __DIR__ . '/../../../../../app.php';

use App\Models\Admin;
use App\Models\Teacher;
use App\Models\WeeklyPlan2;
use Classes\Server;
use Classes\Session;
use Classes\Util;

Session::is_logged();
Server::is_post();

$teacher = Teacher::find(Session::id());
$school = Admin::primaryAdmin();
$year = $school->year;

// Get weekly plan
if (isset($_POST['getWeeklyPlan'])) {
    $planId = $_POST['getWeeklyPlan'];
    $weeklyPlan = WeeklyPlan2::find($planId);

    if ($weeklyPlan && $weeklyPlan->id == $teacher->id) {
        echo Util::toJson($weeklyPlan);
    } else {
        http_response_code(404);
        echo Util::toJson(['error' => __('Plan no encontrado')]);
    }
    exit;
}

// Create weekly plan
if (isset($_POST['createWeeklyPlan'])) {
    $weeklyPlan = WeeklyPlan2::create([
        'id' => $teacher->id,
        'year' => $year,
        'asignatura' => $_POST['asignatura'] ?? '',
        'grado' => $_POST['grado'] ?? '',
        'fecha' => $_POST['fecha'] ?? '',
        'desde' => $_POST['desde'] ?? '',
        'hasta' => $_POST['hasta'] ?? '',
        'tema' => $_POST['tema'] ?? '',
        'estandares1' => $_POST['estandares1'] ?? '',
        'estandares2' => $_POST['estandares2'] ?? '',
        'estandares3' => $_POST['estandares3'] ?? '',
        'objetivos1' => $_POST['objetivos1'] ?? '',
        'objetivos2' => $_POST['objetivos2'] ?? '',
        'objetivos3' => $_POST['objetivos3'] ?? '',
        'objetivos4' => $_POST['objetivos4'] ?? '',
        'destrezas1' => $_POST['destrezas1'] ?? '',
        'destrezas2' => $_POST['destrezas2'] ?? '',
        'destrezas3' => $_POST['destrezas3'] ?? '',
        'destrezas4' => $_POST['destrezas4'] ?? '',
        'estand_comun1' => $_POST['estand_comun1'] ?? '',
        'estand_comun2' => $_POST['estand_comun2'] ?? '',
        'estand_comun3' => $_POST['estand_comun3'] ?? '',
        'estand_comun4' => $_POST['estand_comun4'] ?? '',
        'apoyo1' => $_POST['apoyo1'] ?? '',
        'apoyo2' => $_POST['apoyo2'] ?? '',
        'apoyo3' => $_POST['apoyo3'] ?? '',
        'apoyo4' => $_POST['apoyo4'] ?? '',
        'apoyo5' => $_POST['apoyo5'] ?? '',
        'apoyo6' => $_POST['apoyo6'] ?? '',
        'apoyo7' => $_POST['apoyo7'] ?? '',
        'apoyo8' => $_POST['apoyo8'] ?? '',
        'apoyo9' => $_POST['apoyo9'] ?? '',
        'apoyo10' => $_POST['apoyo10'] ?? '',
        'apoyo11' => $_POST['apoyo11'] ?? '',
        'apoyo12' => $_POST['apoyo12'] ?? '',
        'apoyo13' => $_POST['apoyo13'] ?? '',
        'apoyo14' => $_POST['apoyo14'] ?? '',
        'apoyo15' => $_POST['apoyo15'] ?? '',
        'apoyo16' => $_POST['apoyo16'] ?? '',
        'apoyo17' => $_POST['apoyo17'] ?? '',
        'apoyo18' => $_POST['apoyo18'] ?? '',
        'apoyo19' => $_POST['apoyo19'] ?? '',
        'apoyo20' => $_POST['apoyo20'] ?? '',
        'apoyo21' => $_POST['apoyo21'] ?? '',
        'apoyo22' => $_POST['apoyo22'] ?? '',
        'apoyo23' => $_POST['apoyo23'] ?? '',
        'apoyo24' => $_POST['apoyo24'] ?? '',
        'apoyo25' => $_POST['apoyo25'] ?? '',
        'apoyo26' => $_POST['apoyo26'] ?? '',
        'apoyo27' => $_POST['apoyo27'] ?? '',
        'integracion1' => $_POST['integracion1'] ?? '',
        'integracion2' => $_POST['integracion2'] ?? '',
        'integracion3' => $_POST['integracion3'] ?? '',
        'integracion4' => $_POST['integracion4'] ?? '',
        'integracion5' => $_POST['integracion5'] ?? '',
        'integracion6' => $_POST['integracion6'] ?? '',
        'integracion7' => $_POST['integracion7'] ?? '',
        'integracion8' => $_POST['integracion8'] ?? '',
        'integracion9' => $_POST['integracion9'] ?? '',
        'integracion10' => $_POST['integracion10'] ?? '',
        'integracion11' => $_POST['integracion11'] ?? '',
        'integracion12' => $_POST['integracion12'] ?? '',
        'estrategias1' => $_POST['estrategias1'] ?? '',
        'estrategias2' => $_POST['estrategias2'] ?? '',
        'estrategias3' => $_POST['estrategias3'] ?? '',
        'estrategias4' => $_POST['estrategias4'] ?? '',
        'estrategias5' => $_POST['estrategias5'] ?? '',
        'estrategias6' => $_POST['estrategias6'] ?? '',
        'estrategias7' => $_POST['estrategias7'] ?? '',
        'estrategias8' => $_POST['estrategias8'] ?? '',
        'estrategias9' => $_POST['estrategias9'] ?? '',
        'estrategias10' => $_POST['estrategias10'] ?? '',
        'estrategias11' => $_POST['estrategias11'] ?? '',
        'estrategias12' => $_POST['estrategias12'] ?? '',
        'estrategias13' => $_POST['estrategias13'] ?? '',
        'estrategias14' => $_POST['estrategias14'] ?? '',
        'estrategias15' => $_POST['estrategias15'] ?? '',
        'portafolio1' => $_POST['portafolio1'] ?? '',
        'portafolio2' => $_POST['portafolio2'] ?? '',
        'prueba1' => $_POST['prueba1'] ?? '',
        'prueba2' => $_POST['prueba2'] ?? '',
        'proyecto1' => $_POST['proyecto1'] ?? '',
        'proyecto2' => $_POST['proyecto2'] ?? '',
        'contestar1' => $_POST['contestar1'] ?? '',
        'contestar2' => $_POST['contestar2'] ?? '',
        'valores1' => $_POST['valores1'] ?? '',
        'valores2' => $_POST['valores2'] ?? '',
        'valores3' => $_POST['valores3'] ?? '',
        'valores4' => $_POST['valores4'] ?? '',
        'valores5' => $_POST['valores5'] ?? '',
        'valores6' => $_POST['valores6'] ?? '',
        'valores7' => $_POST['valores7'] ?? '',
        'valores8' => $_POST['valores8'] ?? '',
        'valores9' => $_POST['valores9'] ?? '',
        'valores10' => $_POST['valores10'] ?? '',
        'valores11' => $_POST['valores11'] ?? '',
        'valores12' => $_POST['valores12'] ?? '',
        'valores13' => $_POST['valores13'] ?? '',
        'valores14' => $_POST['valores14'] ?? '',
        'valores15' => $_POST['valores15'] ?? '',
        'valores16' => $_POST['valores16'] ?? '',
        'valores17' => $_POST['valores17'] ?? '',
        'valores18' => $_POST['valores18'] ?? '',
        'valores19' => $_POST['valores19'] ?? '',
        'valores20' => $_POST['valores20'] ?? '',
        'valores21' => $_POST['valores21'] ?? '',
        'valores22' => $_POST['valores22'] ?? '',
        'acomodo1' => $_POST['acomodo1'] ?? '',
        'acomodo2' => $_POST['acomodo2'] ?? '',
        'acomodo3' => $_POST['acomodo3'] ?? '',
        'acomodo4' => $_POST['acomodo4'] ?? '',
        'acomodo5' => $_POST['acomodo5'] ?? '',
        'acomodo6' => $_POST['acomodo6'] ?? '',
        'acomodo1_1' => $_POST['acomodo1_1'] ?? '',
        'acomodo1_2' => $_POST['acomodo1_2'] ?? '',
        'acomodo2_1' => $_POST['acomodo2_1'] ?? '',
        'acomodo2_2' => $_POST['acomodo2_2'] ?? '',
        'acomodo3_1' => $_POST['acomodo3_1'] ?? '',
        'acomodo3_2' => $_POST['acomodo3_2'] ?? '',
        'acomodo4_1' => $_POST['acomodo4_1'] ?? '',
        'acomodo4_2' => $_POST['acomodo4_2'] ?? '',
        'acomodo5_1' => $_POST['acomodo5_1'] ?? '',
        'acomodo5_2' => $_POST['acomodo5_2'] ?? '',
        'acomodo6_1' => $_POST['acomodo6_1'] ?? '',
        'acomodo6_2' => $_POST['acomodo6_2'] ?? '',
        'semanal1_1' => $_POST['semanal1_1'] ?? '',
        'semanal1_2' => $_POST['semanal1_2'] ?? '',
        'semanal1_3' => $_POST['semanal1_3'] ?? '',
        'semanal2_1' => $_POST['semanal2_1'] ?? '',
        'semanal2_2' => $_POST['semanal2_2'] ?? '',
        'semanal2_3' => $_POST['semanal2_3'] ?? '',
        'semanal3_1' => $_POST['semanal3_1'] ?? '',
        'semanal3_2' => $_POST['semanal3_2'] ?? '',
        'semanal3_3' => $_POST['semanal3_3'] ?? '',
        'semanal4_1' => $_POST['semanal4_1'] ?? '',
        'semanal4_2' => $_POST['semanal4_2'] ?? '',
        'semanal4_3' => $_POST['semanal4_3'] ?? '',
        'semanal5_1' => $_POST['semanal5_1'] ?? '',
        'semanal5_2' => $_POST['semanal5_2'] ?? '',
        'semanal5_3' => $_POST['semanal5_3'] ?? '',
        'semanal6_1' => $_POST['semanal6_1'] ?? '',
        'semanal6_2' => $_POST['semanal6_2'] ?? '',
        'semanal6_3' => $_POST['semanal6_3'] ?? '',
        'semanal7_1' => $_POST['semanal7_1'] ?? '',
        'semanal7_2' => $_POST['semanal7_2'] ?? '',
        'semanal7_3' => $_POST['semanal7_3'] ?? '',
        'semanal8_1' => $_POST['semanal8_1'] ?? '',
        'semanal8_2' => $_POST['semanal8_2'] ?? '',
        'semanal8_3' => $_POST['semanal8_3'] ?? '',
        'semanal9_1' => $_POST['semanal9_1'] ?? '',
        'semanal9_2' => $_POST['semanal9_2'] ?? '',
        'semanal9_3' => $_POST['semanal9_3'] ?? '',
        'semanal10_1' => $_POST['semanal10_1'] ?? '',
        'semanal10_2' => $_POST['semanal10_2'] ?? '',
        'semanal10_3' => $_POST['semanal10_3'] ?? '',
        'revisado1' => $_POST['revisado1'] ?? '',
        'revisado2' => $_POST['revisado2'] ?? '',
        'revisado3' => $_POST['revisado3'] ?? '',
        'revisado4' => $_POST['revisado4'] ?? '',
        'revisado5' => $_POST['revisado5'] ?? '',
    ]);

    echo Util::toJson(['success' => true, 'id' => $weeklyPlan->id2]);
    exit;
}

// Update weekly plan
if (isset($_POST['updateWeeklyPlan'])) {
    $weeklyPlanId = $_POST['weeklyPlanId'];
    $weeklyPlan = WeeklyPlan2::find($weeklyPlanId);

    if ($weeklyPlan && $weeklyPlan->id == $teacher->id) {
        $weeklyPlan->update([
            'asignatura' => $_POST['asignatura'] ?? '',
            'grado' => $_POST['grado'] ?? '',
            'fecha' => $_POST['fecha'] ?? '',
            'desde' => $_POST['desde'] ?? '',
            'hasta' => $_POST['hasta'] ?? '',
            'tema' => $_POST['tema'] ?? '',
            'estandares1' => $_POST['estandares1'] ?? '',
            'estandares2' => $_POST['estandares2'] ?? '',
            'estandares3' => $_POST['estandares3'] ?? '',
            'objetivos1' => $_POST['objetivos1'] ?? '',
            'objetivos2' => $_POST['objetivos2'] ?? '',
            'objetivos3' => $_POST['objetivos3'] ?? '',
            'objetivos4' => $_POST['objetivos4'] ?? '',
            'destrezas1' => $_POST['destrezas1'] ?? '',
            'destrezas2' => $_POST['destrezas2'] ?? '',
            'destrezas3' => $_POST['destrezas3'] ?? '',
            'destrezas4' => $_POST['destrezas4'] ?? '',
            'estand_comun1' => $_POST['estand_comun1'] ?? '',
            'estand_comun2' => $_POST['estand_comun2'] ?? '',
            'estand_comun3' => $_POST['estand_comun3'] ?? '',
            'estand_comun4' => $_POST['estand_comun4'] ?? '',
            'apoyo1' => $_POST['apoyo1'] ?? '',
            'apoyo2' => $_POST['apoyo2'] ?? '',
            'apoyo3' => $_POST['apoyo3'] ?? '',
            'apoyo4' => $_POST['apoyo4'] ?? '',
            'apoyo5' => $_POST['apoyo5'] ?? '',
            'apoyo6' => $_POST['apoyo6'] ?? '',
            'apoyo7' => $_POST['apoyo7'] ?? '',
            'apoyo8' => $_POST['apoyo8'] ?? '',
            'apoyo9' => $_POST['apoyo9'] ?? '',
            'apoyo10' => $_POST['apoyo10'] ?? '',
            'apoyo11' => $_POST['apoyo11'] ?? '',
            'apoyo12' => $_POST['apoyo12'] ?? '',
            'apoyo13' => $_POST['apoyo13'] ?? '',
            'apoyo14' => $_POST['apoyo14'] ?? '',
            'apoyo15' => $_POST['apoyo15'] ?? '',
            'apoyo16' => $_POST['apoyo16'] ?? '',
            'apoyo17' => $_POST['apoyo17'] ?? '',
            'apoyo18' => $_POST['apoyo18'] ?? '',
            'apoyo19' => $_POST['apoyo19'] ?? '',
            'apoyo20' => $_POST['apoyo20'] ?? '',
            'apoyo21' => $_POST['apoyo21'] ?? '',
            'apoyo22' => $_POST['apoyo22'] ?? '',
            'apoyo23' => $_POST['apoyo23'] ?? '',
            'apoyo24' => $_POST['apoyo24'] ?? '',
            'apoyo25' => $_POST['apoyo25'] ?? '',
            'apoyo26' => $_POST['apoyo26'] ?? '',
            'apoyo27' => $_POST['apoyo27'] ?? '',
            'integracion1' => $_POST['integracion1'] ?? '',
            'integracion2' => $_POST['integracion2'] ?? '',
            'integracion3' => $_POST['integracion3'] ?? '',
            'integracion4' => $_POST['integracion4'] ?? '',
            'integracion5' => $_POST['integracion5'] ?? '',
            'integracion6' => $_POST['integracion6'] ?? '',
            'integracion7' => $_POST['integracion7'] ?? '',
            'integracion8' => $_POST['integracion8'] ?? '',
            'integracion9' => $_POST['integracion9'] ?? '',
            'integracion10' => $_POST['integracion10'] ?? '',
            'integracion11' => $_POST['integracion11'] ?? '',
            'integracion12' => $_POST['integracion12'] ?? '',
            'estrategias1' => $_POST['estrategias1'] ?? '',
            'estrategias2' => $_POST['estrategias2'] ?? '',
            'estrategias3' => $_POST['estrategias3'] ?? '',
            'estrategias4' => $_POST['estrategias4'] ?? '',
            'estrategias5' => $_POST['estrategias5'] ?? '',
            'estrategias6' => $_POST['estrategias6'] ?? '',
            'estrategias7' => $_POST['estrategias7'] ?? '',
            'estrategias8' => $_POST['estrategias8'] ?? '',
            'estrategias9' => $_POST['estrategias9'] ?? '',
            'estrategias10' => $_POST['estrategias10'] ?? '',
            'estrategias11' => $_POST['estrategias11'] ?? '',
            'estrategias12' => $_POST['estrategias12'] ?? '',
            'estrategias13' => $_POST['estrategias13'] ?? '',
            'estrategias14' => $_POST['estrategias14'] ?? '',
            'estrategias15' => $_POST['estrategias15'] ?? '',
            'portafolio1' => $_POST['portafolio1'] ?? '',
            'portafolio2' => $_POST['portafolio2'] ?? '',
            'prueba1' => $_POST['prueba1'] ?? '',
            'prueba2' => $_POST['prueba2'] ?? '',
            'proyecto1' => $_POST['proyecto1'] ?? '',
            'proyecto2' => $_POST['proyecto2'] ?? '',
            'contestar1' => $_POST['contestar1'] ?? '',
            'contestar2' => $_POST['contestar2'] ?? '',
            'valores1' => $_POST['valores1'] ?? '',
            'valores2' => $_POST['valores2'] ?? '',
            'valores3' => $_POST['valores3'] ?? '',
            'valores4' => $_POST['valores4'] ?? '',
            'valores5' => $_POST['valores5'] ?? '',
            'valores6' => $_POST['valores6'] ?? '',
            'valores7' => $_POST['valores7'] ?? '',
            'valores8' => $_POST['valores8'] ?? '',
            'valores9' => $_POST['valores9'] ?? '',
            'valores10' => $_POST['valores10'] ?? '',
            'valores11' => $_POST['valores11'] ?? '',
            'valores12' => $_POST['valores12'] ?? '',
            'valores13' => $_POST['valores13'] ?? '',
            'valores14' => $_POST['valores14'] ?? '',
            'valores15' => $_POST['valores15'] ?? '',
            'valores16' => $_POST['valores16'] ?? '',
            'valores17' => $_POST['valores17'] ?? '',
            'valores18' => $_POST['valores18'] ?? '',
            'valores19' => $_POST['valores19'] ?? '',
            'valores20' => $_POST['valores20'] ?? '',
            'valores21' => $_POST['valores21'] ?? '',
            'valores22' => $_POST['valores22'] ?? '',
            'acomodo1' => $_POST['acomodo1'] ?? '',
            'acomodo2' => $_POST['acomodo2'] ?? '',
            'acomodo3' => $_POST['acomodo3'] ?? '',
            'acomodo4' => $_POST['acomodo4'] ?? '',
            'acomodo5' => $_POST['acomodo5'] ?? '',
            'acomodo6' => $_POST['acomodo6'] ?? '',
            'acomodo1_1' => $_POST['acomodo1_1'] ?? '',
            'acomodo1_2' => $_POST['acomodo1_2'] ?? '',
            'acomodo2_1' => $_POST['acomodo2_1'] ?? '',
            'acomodo2_2' => $_POST['acomodo2_2'] ?? '',
            'acomodo3_1' => $_POST['acomodo3_1'] ?? '',
            'acomodo3_2' => $_POST['acomodo3_2'] ?? '',
            'acomodo4_1' => $_POST['acomodo4_1'] ?? '',
            'acomodo4_2' => $_POST['acomodo4_2'] ?? '',
            'acomodo5_1' => $_POST['acomodo5_1'] ?? '',
            'acomodo5_2' => $_POST['acomodo5_2'] ?? '',
            'acomodo6_1' => $_POST['acomodo6_1'] ?? '',
            'acomodo6_2' => $_POST['acomodo6_2'] ?? '',
            'semanal1_1' => $_POST['semanal1_1'] ?? '',
            'semanal1_2' => $_POST['semanal1_2'] ?? '',
            'semanal1_3' => $_POST['semanal1_3'] ?? '',
            'semanal2_1' => $_POST['semanal2_1'] ?? '',
            'semanal2_2' => $_POST['semanal2_2'] ?? '',
            'semanal2_3' => $_POST['semanal2_3'] ?? '',
            'semanal3_1' => $_POST['semanal3_1'] ?? '',
            'semanal3_2' => $_POST['semanal3_2'] ?? '',
            'semanal3_3' => $_POST['semanal3_3'] ?? '',
            'semanal4_1' => $_POST['semanal4_1'] ?? '',
            'semanal4_2' => $_POST['semanal4_2'] ?? '',
            'semanal4_3' => $_POST['semanal4_3'] ?? '',
            'semanal5_1' => $_POST['semanal5_1'] ?? '',
            'semanal5_2' => $_POST['semanal5_2'] ?? '',
            'semanal5_3' => $_POST['semanal5_3'] ?? '',
            'semanal6_1' => $_POST['semanal6_1'] ?? '',
            'semanal6_2' => $_POST['semanal6_2'] ?? '',
            'semanal6_3' => $_POST['semanal6_3'] ?? '',
            'semanal7_1' => $_POST['semanal7_1'] ?? '',
            'semanal7_2' => $_POST['semanal7_2'] ?? '',
            'semanal7_3' => $_POST['semanal7_3'] ?? '',
            'semanal8_1' => $_POST['semanal8_1'] ?? '',
            'semanal8_2' => $_POST['semanal8_2'] ?? '',
            'semanal8_3' => $_POST['semanal8_3'] ?? '',
            'semanal9_1' => $_POST['semanal9_1'] ?? '',
            'semanal9_2' => $_POST['semanal9_2'] ?? '',
            'semanal9_3' => $_POST['semanal9_3'] ?? '',
            'semanal10_1' => $_POST['semanal10_1'] ?? '',
            'semanal10_2' => $_POST['semanal10_2'] ?? '',
            'semanal10_3' => $_POST['semanal10_3'] ?? '',
            'revisado1' => $_POST['revisado1'] ?? '',
            'revisado2' => $_POST['revisado2'] ?? '',
            'revisado3' => $_POST['revisado3'] ?? '',
            'revisado4' => $_POST['revisado4'] ?? '',
            'revisado5' => $_POST['revisado5'] ?? '',
        ]);

        echo Util::toJson(['success' => true, 'id' => $weeklyPlan->id2]);
    } else {
        echo Util::toJson(['success' => false, 'message' => 'Plan semanal no encontrado']);
    }
    exit;
}

// Delete weekly plan
if (isset($_POST['deleteWeeklyPlan'])) {
    $weeklyPlanId = $_POST['deleteWeeklyPlan'];
    $weeklyPlan = WeeklyPlan2::find($weeklyPlanId);

    if ($weeklyPlan && $weeklyPlan->id == $teacher->id) {
        $weeklyPlan->delete();
        echo Util::toJson(['success' => true]);
    } else {
        echo Util::toJson(['success' => false, 'message' => 'Plan semanal no encontrado']);
    }
    exit;
}
